// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_authorization.cpp"
#include "EWIEGA46WW/moc_ball.cpp"
#include "EWIEGA46WW/moc_breakout.cpp"
#include "EWIEGA46WW/moc_brick.cpp"
#include "EWIEGA46WW/moc_game.cpp"
#include "EWIEGA46WW/moc_menu.cpp"
#include "EWIEGA46WW/moc_paddle.cpp"
#include "EWIEGA46WW/moc_snake.cpp"
